services:
  app:
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_DB=0
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/marriage_gifts
      - EMAIL_HOST_USER=dev@example.com
      - EMAIL_HOST_PASSWORD=devpassword
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - DEFAULT_FROM_EMAIL=dev@example.com
